language: java
jdk: openjdk8

services:
  - docker

before_install:
  - chmod +x mvnw

script:
  - ./mvnw clean install -DskipTests=true -Dmaven.javadoc.skip=true dependency:copy-dependencies -DoutputDirectory=target/dependencies -B -V
  - ./mvnw test -B
  - docker build -t user-security-service:1.0.0 .
